name: windows_clipboard
description: Clipboard implementation on windows. There are simple read to use wrappers or you can call the functions manually.
version: 1.0.2
homepage: https://github.com/Hexer10/windows_clipboard

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  ffi: ^0.1.3
#  path: ^1.6.0

dev_dependencies:
  effective_dart: ^1.2.0
